### ISSUE TITLE
Error running Demo via GPTune Lite

### ISSUE THREAD

**Issue by huttered40** [gptune/GPTune#16]
Hi, I follow the instructions verbatim from the Documentation for installing GPTune Lite.
When I go to run the demo script, I get the following error:
```
login3.stampede2(1071)$ python ./demo.py -nrun 20
Traceback (most recent call last):
  File "./demo.py", line 43, in <module>
    from autotune.search import *
  File "/home1/05608/tg849075/.local/lib/python3.8/site-packages/autotune/__init__.py", line 5, in <module>
    import autotune.problem
  File "/home1/05608/tg849075/.local/lib/python3.8/site-packages/autotune/problem.py", line 43
    input_space: Space,
               ^
SyntaxError: invalid syntax
```

I have loaded Python3/3.8.2. The machine I am running on is a login node of TACC Stampede2.

Any idea why this is throwing an error?

**Comment by huttered40** [comment]
This problem has been resolved.
